In [1]:
import torch
import numpy as np
import pandas as pd

In [2]:
x=torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.shape

torch.Size([12])

In [4]:
x.numel()

12

In [5]:
x = x.reshape(3,4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [6]:
y=torch.tensor([
[ 0,  1,  2,  3],
[ 4,  5,  6,  7],
[ 8,  9, 10, 11]
])
y

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [7]:
a=torch.arange(12,dtype=torch.float32).reshape(3,4)
b=torch.arange(13,25,dtype=torch.float32).reshape(3,4)
torch.cat((a,b),dim=0),torch.cat((a,b),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [13., 14., 15., 16.],
         [17., 18., 19., 20.],
         [21., 22., 23., 24.]]),
 tensor([[ 0.,  1.,  2.,  3., 13., 14., 15., 16.],
         [ 4.,  5.,  6.,  7., 17., 18., 19., 20.],
         [ 8.,  9., 10., 11., 21., 22., 23., 24.]]))

In [8]:
a==b # 生成二元矩阵

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [9]:
a.sum()

tensor(66.)

In [10]:
a+b # 对应相加

tensor([[13., 15., 17., 19.],
        [21., 23., 25., 27.],
        [29., 31., 33., 35.]])

In [11]:
# 广播机制，
# 形状不同的矩阵操作
c=torch.arange(3).reshape(3,1)
d=torch.arange(2).reshape(1,2)
c,d

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [12]:
c + d # 会复制变成两个（3，2）的矩阵

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [13]:
# 元素访问
a[0,0],b[2,1]

(tensor(0.), tensor(22.))

In [14]:
a[0,0]=1
a

tensor([[ 1.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [15]:
b[1:3,1:3] = 0
b

tensor([[13., 14., 15., 16.],
        [17.,  0.,  0., 20.],
        [21.,  0.,  0., 24.]])

有些操作会让结果重新分配内存

In [16]:
# e.g. 重新分配的
# id 类似于指针、地址
p = id(a)
a = a+b
p == id(a)

False

In [17]:
# 原地操作
z = torch.zeros_like(a)
print(id(z))
z[:] = a + b # 用z[:]相当于改变里面的值而不会重新分配内存
print(id(z))

2198136516976
2198136516976


In [18]:
p = id(a)
a += b 
p == id(a)

True