
标量由只有一个元素的张量表示


In [1]:
import torch

x = torch.tensor([3.0])
y = torch.tensor([2.0])

x+y,x*y,x/y,x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))


向量可视为标量值组成的列表


In [2]:
x = torch.tensor([1,2,3])
x,x[2]

(tensor([1, 2, 3]), tensor(3))

In [3]:
# 访问张量长度,形状
len(x),x.shape

(3, torch.Size([3]))


矩阵可视为向量组成的列表


In [4]:
A = torch.arange(20).reshape((5,4))
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [5]:
# 矩阵的转置
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [6]:
# 更高维的结构
X = torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

矩阵运算

In [7]:
# 矩阵运算
A = torch.arange(20).reshape(4,5)
B = A.clone() # 重新分配内存给 B
A,A+B

(tensor([[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]),
 tensor([[ 0,  2,  4,  6,  8],
         [10, 12, 14, 16, 18],
         [20, 22, 24, 26, 28],
         [30, 32, 34, 36, 38]]))

In [8]:
# 哈达玛积
# 并非矩阵乘法，而是将对应位置的元素相乘后填回位置
A*B

tensor([[  0,   1,   4,   9,  16],
        [ 25,  36,  49,  64,  81],
        [100, 121, 144, 169, 196],
        [225, 256, 289, 324, 361]])

In [9]:
A = torch.arange(40).reshape(2,5,4)
A,A.sum()

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11],
          [12, 13, 14, 15],
          [16, 17, 18, 19]],
 
         [[20, 21, 22, 23],
          [24, 25, 26, 27],
          [28, 29, 30, 31],
          [32, 33, 34, 35],
          [36, 37, 38, 39]]]),
 tensor(780))

按轴对张量求和

In [10]:
A = torch.arange(40,dtype=float).reshape(2,5,4)
A_sum_axis0 = A.sum(axis = 0) # 从第0维度求和，去掉2，生成（5，4）的矩阵（将正方形从0轴拍扁）
A_sum_axis0,A_sum_axis0.shape

(tensor([[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]], dtype=torch.float64),
 torch.Size([5, 4]))

In [11]:
# 沿两个维度求和（拍扁2次）
A_sum_axis01 = A.sum(axis=[0,1])
A_sum_axis01

tensor([180., 190., 200., 210.], dtype=torch.float64)

In [12]:
# 平均值
A.mean(dtype = float),A.sum()/A.numel()

(tensor(19.5000, dtype=torch.float64), tensor(19.5000, dtype=torch.float64))

In [13]:
A.mean(axis=0), A.sum(axis=0)/A.shape[0]

(tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]], dtype=torch.float64),
 tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]], dtype=torch.float64))

In [14]:
# keepdims保持维度不变，方便广播
A.sum(axis = 1,keepdims=True)

tensor([[[ 40.,  45.,  50.,  55.]],

        [[140., 145., 150., 155.]]], dtype=torch.float64)

In [15]:
# 点积 dot,只用于一维向量
# 相同位置的元素相乘后求和,即 A*B的sum
A = torch.arange(4)
B = A.clone()
A,B,torch.dot(A,B),torch.sum(A*B)
# A.dot(B),B.dot(A)

(tensor([0, 1, 2, 3]), tensor([0, 1, 2, 3]), tensor(14), tensor(14))

矩阵乘法

In [16]:
# 矩阵乘法
# 矩阵向量相乘
M = torch.arange(12).reshape(3,4)
V = torch.tensor([1,2,3,4])
M,V,torch.mv(M,V),M.mv(V)# torch.mv()的 m指矩阵，v指向量

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([1, 2, 3, 4]),
 tensor([ 20,  60, 100]),
 tensor([ 20,  60, 100]))

In [17]:
# 矩阵相乘
M_1 = torch.arange(12).reshape(3,4)
M_2 = torch.arange(8).reshape(4,2)
M_1,M_2,torch.mm(M_1,M_2) # M_1.mm(M_2)

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[0, 1],
         [2, 3],
         [4, 5],
         [6, 7]]),
 tensor([[ 28,  34],
         [ 76,  98],
         [124, 162]]))

范数

In [18]:
# L2范数 norm是向量元素平方和的平方根
u = torch.tensor([1.0,2,3,4])
u,torch.norm(u)

(tensor([1., 2., 3., 4.]), tensor(5.4772))

In [19]:
# L1范数指向量元素的绝对值之和
torch.abs(u).sum()

tensor(10.)

In [20]:
# 矩阵的范数
# F范数 norm是矩阵元素的平方和的平方根
torch.norm(torch.ones(4,9))

tensor(6.)