In [1]:
import torch

In [2]:
x = torch.arange(4,dtype = float)
x

tensor([0., 1., 2., 3.], dtype=torch.float64)

In [3]:
x.requires_grad_(True) # x = torch.arange(4,requires_grad_=True)
x.grad # 默认为NONE

In [4]:
y = 2*torch.dot(x,x) # 即 y = 2x^2,此时 y是一个标量
y

tensor(28., dtype=torch.float64, grad_fn=<MulBackward0>)

In [5]:
y.backward()
x.grad # 对y反向求导后，值存在x.grad里

tensor([ 0.,  4.,  8., 12.], dtype=torch.float64)

In [6]:
# pytorch默认会累积梯度，需要先清除之前的值
x.grad.zero_() # 下划线表示写入
y=x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.], dtype=torch.float64)

In [8]:
# 将某些计算移到计算图之外
x.grad.zero_()
y = x * x # 此时y是一个向量
u = y.detach() # detach后 u就是标量了，但 y不变
z = u * x
z.sum().backward()
x.grad == u

tensor([True, True, True, True])