In [1]:
import torch
import torch.nn.functional as F
# 输入的矩阵
input = torch.tensor([
    [1,2,0,3,1],
    [0,1,2,3,1],
    [1,2,1,0,0],
    [5,2,3,1,1],
    [2,1,0,1,1]
])

# 卷积核
kernel = torch.tensor([
    [1,2,1],
    [0,1,0],
    [2,1,0]
])

In [2]:
# torch.nn.functional.conv2d(input, weight, bias=None, stride=1,padding=0,...)
# input – input tensor of shape (minibatch,in_channels,iH,iW)
# weight – filters of shape (out_channels, in_channels/groups, kH, kW)
# 要求 4维

input = torch.reshape(input, (1,1,5,5))
kernel = torch.reshape(kernel,(1,1,3,3))

In [3]:
# stride表示步幅，即卷积核在input上每次移动的格数
output = F.conv2d(input,kernel,stride=1)
output

tensor([[[[10, 12, 12],
          [18, 16, 16],
          [13,  9,  3]]]])

In [4]:
output2 = F.conv2d(input,kernel,stride=2)
output2

tensor([[[[10, 12],
          [13,  3]]]])

In [5]:
# padding 填充，即在input外层填充的圈数，避免边缘效应
output3 = F.conv2d(input,kernel,stride=1,padding=1)
output3

tensor([[[[ 1,  3,  4, 10,  8],
          [ 5, 10, 12, 12,  6],
          [ 7, 18, 16, 16,  8],
          [11, 13,  9,  3,  4],
          [14, 13,  9,  7,  4]]]])